package com.mockinterview.domain.question;

public enum QuestionTopic {
    REDIS, MYSQL, SPRING, KAFKA, JAVA_CONCURRENCY, JVM,
    JAVA_BASICS, JAVA_COLLECTIONS, JAVA_IO, MYBATIS, NETWORK, OS,
    DATA_STRUCTURES, MESSAGE_QUEUE, DISTRIBUTED, SYSTEM_DESIGN, SECURITY, DEVOPS
}
