import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { getToday, getProgress, configureReview, skipToday, startReview, states, type Today, type Overview, type Preferences, type Recommendation } from '../api/review'
import { createPractice, newRequestKey, topics, labels } from '../api/practice'
import { PageHeading, ErrorState, LoadingState } from '../components/Ui'
import Icon from '../components/Icon'
export default function ReviewPage({mode}: {mode:'today'|'review'|'progress'}) {
  const navigate=useNavigate()
  const [today,setToday]=useState<Today|null>(null), [overview,setOverview]=useState<Overview|null>(null)
  const [prefs,setPrefs]=useState<Preferences|null>(null), [error,setError]=useState(''), [actionError,setActionError]=useState('')
  const [reload,setReload]=useState(0), [busy,setBusy]=useState(''), [topic,setTopic]=useState(''), [state,setState]=useState('')
  useEffect(()=>{let cancelled=false;setError('');
    Promise.all([getToday(),getProgress()]).then(([t,p])=>{if(!cancelled){setToday(t);setOverview(p);setPrefs(p.preferences)}})
      .catch(e=>{if(!cancelled)setError(e.message)})
    return ()=>{cancelled=true}
  },[reload,mode])
  async function action(name:string,operation:()=>Promise<unknown>){if(busy)return;setBusy(name);setActionError('');try{await operation();setReload(n=>n+1)}catch(e){setActionError(e instanceof Error?e.message:'操作失败，请重试。')}finally{setBusy('')}}
  async function start(item:Recommendation){await action(item.question.id,async()=>{
    const storage='today-start:'+item.kind+':'+item.question.id+':'+today?.date
    let key=sessionStorage.getItem(storage);if(!key){key=newRequestKey();sessionStorage.setItem(storage,key)}
    const session=item.kind==='REVIEW'&&item.pointId?await startReview(item.pointId,key):await createPractice(item.question,key)
    sessionStorage.removeItem(storage);navigate('/practice/sessions/'+session.id)
  })}
  const titles={today:'今天，练好三分钟里的一个要点。',review:'薄弱点有证据，下一步有方向。',progress:'把当场会答，练成隔几天也能讲清。'}
  if(error&&!today)return <div className="page-scroll"><div className="page-content"><ErrorState message={error} onRetry={()=>setReload(n=>n+1)}/></div></div>
  if(!today||!overview||!prefs)return <div className="page-scroll"><div className="page-content"><LoadingState title="正在整理你的练习计划"/></div></div>
  const points=overview.points.filter(p=>(!topic||p.topic===topic)&&(!state||p.state===state))
  const active=overview.points.filter(p=>p.validAnswers>0).length
  return <div className="page-scroll"><div className="page-content practice-page review-page">
    <PageHeading eyebrow={mode==='today'?'SMALL STEPS, KEPT OVER TIME':'EVIDENCE OF YOUR PRACTICE'} title={titles[mode]} description="练习记录决定下一步。复测默认相隔 1、3、7 天；有辅助重答用于学习，独立复测才累计巩固证据。" action={<Link className="btn btn-ghost" to="/practice/questions">自主选题<Icon name="arrow" size={16}/></Link>}/>
    <nav className="review-tabs" aria-label="练习计划"><Link className={mode==='today'?'active':''} to="/">今日练习</Link><Link className={mode==='review'?'active':''} to="/review">薄弱点与复习</Link><Link className={mode==='progress'?'active':''} to="/progress">进步记录</Link></nav>
    {error&&<p className="error-inline" role="alert">{error}</p>}{actionError&&<p className="error-inline" role="alert">{actionError}</p>}
    <div className="review-summary"><article><span>已练知识点</span><strong>{active}<small> / {overview.points.length}</small></strong></article><article><span>到期复习</span><strong>{today.duePoints}</strong></article><article><span>独立复测通过的要点</span><strong>{overview.independentPasses}</strong></article><article><span>已巩固知识点</span><strong>{overview.points.filter(p=>p.state==='CONSOLIDATED').length}</strong></article></div>
    {mode==='today'&&<>
      <div className="review-section-title"><h2>今天的推荐</h2><span>{today.date} · {prefs.timezone} · 每天 {prefs.dailyLimit} 题</span></div>
      {prefs.paused?<section className="state-card"><h2>复习计划已暂停</h2><p>暂停期间保留到期日期，恢复后按知识点显示一项到期任务。你仍可自主选题。</p><button className="btn btn-primary" disabled={!!busy} onClick={()=>action('resume',()=>configureReview({...prefs,paused:false}))}>恢复推荐</button></section>:today.recommendations.length===0?<section className="state-card"><h2>今天没有待推荐的题目</h2><p>可以休息，也可以自主选题。跳过的推荐明天会重新参与排序。</p><Link className="btn btn-primary" to="/practice/questions">去题库</Link></section>:<div className="question-grid">{today.recommendations.map((item,index)=><article className="question-card review-recommendation" key={item.question.id}><div className="question-meta"><span className="pill neutral">{topics[item.question.topic]}</span><span>{item.kind==='REVIEW'?'独立复测':item.kind==='NEW'?'探索新题':'补齐遗漏'}</span></div><span className="question-number">0{index+1}</span><h2>{item.question.title}</h2><p className="review-reason">{item.reason.replace(new RegExp(' · (' + Object.keys(topics).join('|') + ')$'), '')}</p><p>{item.question.prompt}</p><div className="review-card-actions"><button className="btn btn-primary" disabled={!!busy} onClick={()=>start(item)}>{busy===item.question.id?'正在开始…':item.kind==='REVIEW'?'开始独立复测':'练这一题'}<Icon name="arrow" size={16}/></button><button className="text-button" disabled={!!busy} onClick={()=>action('skip',async()=>{await skipToday(item.question.id)})}>今天先跳过</button></div></article>)}</div>}
      <div className="review-shortcuts"><Link to="/projects"><Icon name="file" size={22}/><div><h3>练自己的项目话术</h3><p>个人贡献、技术选型与结果证据</p></div><Icon name="arrow" size={18}/></Link><Link to="/practice/history"><Icon name="clock" size={22}/><div><h3>继续上次的回答</h3><p>首答、重答与专项追问记录</p></div><Icon name="arrow" size={18}/></Link><Link to="/mock"><Icon name="target" size={22}/><div><h3>完整模拟面试</h3><p>用整场练习检验表达</p></div><Icon name="arrow" size={18}/></Link></div>
    </>}
    {mode==='progress'&&<section className="review-state-chart"><h2>当前知识点状态</h2><p>依据已校验的要点评估与独立复测。未评估和无法判断均不算掌握；图中数量不是面试通过率。</p>{Object.entries(states).map(([key,label])=>{const count=overview.points.filter(p=>p.state===key).length;return <div className="review-chart-row" key={key}><span>{label}</span><div className="review-chart-track"><div className={'review-chart-fill '+key.toLowerCase()} style={{width:`${overview.points.length?count/overview.points.length*100:0}%`}}/></div><strong>{count}</strong></div>})}<div className="review-quality-note">{overview.pendingEvaluations} 次等待或进行中的评估 · {overview.failedEvaluations} 次失败评估 · {overview.uncertainItems} 项无法判断。均未作为巩固证据。</div></section>}
    {mode!=='today'&&<><div className="practice-filters"><label>主题<select value={topic} onChange={e=>setTopic(e.target.value)}><option value="">全部主题</option>{Object.entries(topics).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>掌握状态<select value={state} onChange={e=>setState(e.target.value)}><option value="">全部状态</option>{Object.entries(states).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><span>{points.length} 个知识点</span></div><div className="review-points">{points.map(p=><article key={p.id} className="review-point"><div className="review-point-heading"><div><span className="review-topic">{topics[p.topic]}</span><h2>{p.title}</h2></div><span className={'pill '+(p.state==='CONSOLIDATED'?'':'neutral')}>{states[p.state]}</span></div><div className="review-point-meta"><span>{p.validAnswers} 次有效要点评估</span><span>{p.uncertainAnswers} 次无法判断（未计入掌握）</span><span>{p.independentPasses} 次独立复测通过</span><span>{p.dueDate?`下次复习 ${p.dueDate}${p.dueDate<=today.date?' · 已到期':''}`:'暂无复习安排'}</span></div>{p.lastStatus&&<p>最近一次：{labels[p.lastStatus]}</p>}{p.latestSessionId&&<Link className="text-button" to={'/practice/sessions/'+p.latestSessionId}>回看相关练习</Link>}{p.dueDate&&p.dueDate<=today.date&&!prefs.paused&&<button className="btn btn-ghost" disabled={!!busy} onClick={()=>action(p.id,async()=>{const storage='review-start:'+p.id+':'+today.date;let key=sessionStorage.getItem(storage);if(!key){key=newRequestKey();sessionStorage.setItem(storage,key)}const s=await startReview(p.id,key);sessionStorage.removeItem(storage);navigate('/practice/sessions/'+s.id)})}>独立复测</button>}{p.evidence.length>0&&<details><summary>查看判定依据与进步记录（最近 {p.evidence.length} 次）</summary><ol className="review-evidence">{p.evidence.map(e=><li key={e.evaluationId}><time>{new Date(e.answeredAt).toLocaleString('zh-CN',{timeZone:prefs.timezone})}</time><strong>{labels[e.status]}</strong><span>{e.assisted?'有辅助':e.delayed?'独立复测':'独立练习'}{e.passed?' · 本次计入巩固证据':''}</span>{e.quote&&<blockquote>{e.quote}</blockquote>}<Link to={'/practice/sessions/'+e.sessionId}>核对原回答与反馈</Link></li>)}</ol></details>}</article>)}</div></>}
    <details className="review-settings"><summary>调整练习计划与数据</summary><div className="review-settings-fields"><label>每天推荐题量<input type="number" min={1} max={20} value={prefs.dailyLimit} onChange={e=>setPrefs({...prefs,dailyLimit:Number(e.target.value)})}/></label><label>日期时区<select value={prefs.timezone} onChange={e=>setPrefs({...prefs,timezone:e.target.value})}>{['Asia/Shanghai','UTC','America/Los_Angeles','America/New_York'].map(zone=><option key={zone}>{zone}</option>)}</select></label>{prefs.intervals.map((days,index)=><label key={index}>第 {index+1} 档间隔（天）<input type="number" min={1} max={90} value={days} onChange={e=>setPrefs({...prefs,intervals:prefs.intervals.map((d,i)=>i===index?Number(e.target.value):d)})}/></label>)}<label>巩固所需独立复测<input type="number" min={2} max={5} value={prefs.requiredPasses} onChange={e=>setPrefs({...prefs,requiredPasses:Number(e.target.value)})}/></label></div><p>修改间隔或时区后会按新规则重算进度；原始回答与评估保留。暂停不延长到期日，恢复时不叠加逾期任务。</p><div className="practice-actions"><button className="btn btn-primary" disabled={!!busy} onClick={()=>action('settings',()=>configureReview(prefs))}>保存计划</button><button className="btn btn-ghost" disabled={!!busy} onClick={()=>action('pause',()=>configureReview({...prefs,paused:!prefs.paused}))}>{prefs.paused?'恢复复习':'暂停复习'}</button><a className="text-button" href="/api/data/export" download>导出练习与个人资料</a><Link className="text-button" to="/practice/history">管理与删除练习</Link></div></details>
  </div></div>
}
